theme: jekyll-theme-cayman
title: Horizon Daily
description: AI 驱动的每日资讯精选
baseurl: "/Horizon" # the subpath of your site, e.g. /blog
url: "https://yanyu-whaletech.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
timezone: Asia/Shanghai
future: true # Allow future posts to be published
plugins:
  - jekyll-feed
feed:
  path: feed.xml
exclude:
  - ".github"
  - "node_modules"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
